
// This file has been generated by the GUI designer. Do not modify.
namespace Banshee.Renamer
{
	public partial class RenamerWindow
	{
		private global::Gtk.VBox vboxMain;
		private global::Gtk.Frame framePattern;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.Table layoutPattern;
		private global::Gtk.Button btnAdd;
		private global::Gtk.Entry entryPattern;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.NodeView tableStoredPatterns;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Button btnDelete;
		private global::Gtk.ComboBox cbCompiler;
		private global::Gtk.Label lblPattern;
		private global::Gtk.Frame frameGuide;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TextView tvGuide;
		private global::Gtk.Label lblGuide;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment GtkAlignment4;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textview1;
		private global::Gtk.Label lblResults;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Banshee.Renamer.RenamerWindow
			this.Name = "Banshee.Renamer.RenamerWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("RenamerWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Banshee.Renamer.RenamerWindow.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox ();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.framePattern = new global::Gtk.Frame ();
			this.framePattern.Name = "framePattern";
			this.framePattern.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child framePattern.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.layoutPattern = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.layoutPattern.Name = "layoutPattern";
			this.layoutPattern.RowSpacing = ((uint)(6));
			this.layoutPattern.ColumnSpacing = ((uint)(6));
			// Container child layoutPattern.Gtk.Table+TableChild
			this.btnAdd = new global::Gtk.Button ();
			this.btnAdd.CanFocus = true;
			this.btnAdd.Name = "btnAdd";
			this.btnAdd.UseUnderline = true;
			this.btnAdd.Label = global::Mono.Unix.Catalog.GetString ("_Add");
			this.layoutPattern.Add (this.btnAdd);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.layoutPattern [this.btnAdd]));
			w1.LeftAttach = ((uint)(2));
			w1.RightAttach = ((uint)(3));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child layoutPattern.Gtk.Table+TableChild
			this.entryPattern = new global::Gtk.Entry ();
			this.entryPattern.CanFocus = true;
			this.entryPattern.Name = "entryPattern";
			this.entryPattern.IsEditable = true;
			this.entryPattern.InvisibleChar = '•';
			this.layoutPattern.Add (this.entryPattern);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.layoutPattern [this.entryPattern]));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child layoutPattern.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.tableStoredPatterns = new global::Gtk.NodeView ();
			this.tableStoredPatterns.CanFocus = true;
			this.tableStoredPatterns.Name = "tableStoredPatterns";
			this.GtkScrolledWindow1.Add (this.tableStoredPatterns);
			this.layoutPattern.Add (this.GtkScrolledWindow1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.layoutPattern [this.GtkScrolledWindow1]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(3));
			w4.RightAttach = ((uint)(2));
			// Container child layoutPattern.Gtk.Table+TableChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnDelete = new global::Gtk.Button ();
			this.btnDelete.CanFocus = true;
			this.btnDelete.Name = "btnDelete";
			this.btnDelete.UseUnderline = true;
			this.btnDelete.Label = global::Mono.Unix.Catalog.GetString ("_Delete");
			this.vbox2.Add (this.btnDelete);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnDelete]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.cbCompiler = global::Gtk.ComboBox.NewText ();
			this.cbCompiler.Name = "cbCompiler";
			this.vbox2.Add (this.cbCompiler);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.cbCompiler]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.layoutPattern.Add (this.vbox2);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.layoutPattern [this.vbox2]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment2.Add (this.layoutPattern);
			this.framePattern.Add (this.GtkAlignment2);
			this.lblPattern = new global::Gtk.Label ();
			this.lblPattern.Name = "lblPattern";
			this.lblPattern.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Pattern:</b>");
			this.lblPattern.UseMarkup = true;
			this.framePattern.LabelWidget = this.lblPattern;
			this.vboxMain.Add (this.framePattern);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.framePattern]));
			w10.Position = 0;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.frameGuide = new global::Gtk.Frame ();
			this.frameGuide.Name = "frameGuide";
			this.frameGuide.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frameGuide.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.tvGuide = new global::Gtk.TextView ();
			this.tvGuide.CanFocus = true;
			this.tvGuide.Name = "tvGuide";
			this.tvGuide.Editable = false;
			this.tvGuide.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow2.Add (this.tvGuide);
			this.GtkAlignment3.Add (this.GtkScrolledWindow2);
			this.frameGuide.Add (this.GtkAlignment3);
			this.lblGuide = new global::Gtk.Label ();
			this.lblGuide.Name = "lblGuide";
			this.lblGuide.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Guide:</b>");
			this.lblGuide.UseMarkup = true;
			this.frameGuide.LabelWidget = this.lblGuide;
			this.vboxMain.Add (this.frameGuide);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.frameGuide]));
			w14.Position = 1;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.Buffer.Text = "Just some text... What the hell???";
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.Editable = false;
			this.GtkScrolledWindow.Add (this.textview1);
			this.GtkAlignment4.Add (this.GtkScrolledWindow);
			this.frame3.Add (this.GtkAlignment4);
			this.lblResults = new global::Gtk.Label ();
			this.lblResults.Name = "lblResults";
			this.lblResults.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Results</b>");
			this.lblResults.UseMarkup = true;
			this.frame3.LabelWidget = this.lblResults;
			this.vboxMain.Add (this.frame3);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.frame3]));
			w18.Position = 2;
			this.Add (this.vboxMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 503;
			this.DefaultHeight = 576;
			this.Show ();
			this.entryPattern.Changed += new global::System.EventHandler (this.OnPatternChanged);
		}
	}
}
