
// This file has been generated by the GUI designer. Do not modify.
namespace Banshee.Renamer
{
	public partial class RenamingProgressDialog
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label lblRenamingTitle;
		private global::Gtk.ProgressBar pbRenaming;
		private global::Gtk.Expander expndrMessages;
		private global::Gtk.ScrolledWindow scrlMessages;
		private global::Gtk.TextView tvMessages;
		private global::Gtk.Label lblMessages;
		private global::Gtk.Label lblNewFilename;
		private global::Gtk.Label lblNewFilenameTitle;
		private global::Gtk.Label lblOriginalFilename;
		private global::Gtk.Label lblOriginalFilenameTitle;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Banshee.Renamer.RenamingProgressDialog
			this.Name = "Banshee.Renamer.RenamingProgressDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Renaming files...");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child Banshee.Renamer.RenamingProgressDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblRenamingTitle = new global::Gtk.Label ();
			this.lblRenamingTitle.Name = "lblRenamingTitle";
			this.lblRenamingTitle.Xalign = 0F;
			this.lblRenamingTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Renaming selected songs:</b>");
			this.lblRenamingTitle.UseMarkup = true;
			this.lblRenamingTitle.Ellipsize = ((global::Pango.EllipsizeMode)(3));
			this.vbox2.Add (this.lblRenamingTitle);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblRenamingTitle]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.pbRenaming = new global::Gtk.ProgressBar ();
			this.pbRenaming.Name = "pbRenaming";
			this.vbox2.Add (this.pbRenaming);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.pbRenaming]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.expndrMessages = new global::Gtk.Expander (null);
			this.expndrMessages.CanFocus = true;
			this.expndrMessages.Name = "expndrMessages";
			// Container child expndrMessages.Gtk.Container+ContainerChild
			this.scrlMessages = new global::Gtk.ScrolledWindow ();
			this.scrlMessages.HeightRequest = 200;
			this.scrlMessages.Name = "scrlMessages";
			this.scrlMessages.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrlMessages.Gtk.Container+ContainerChild
			this.tvMessages = new global::Gtk.TextView ();
			this.tvMessages.CanFocus = true;
			this.tvMessages.Name = "tvMessages";
			this.tvMessages.Editable = false;
			this.scrlMessages.Add (this.tvMessages);
			this.expndrMessages.Add (this.scrlMessages);
			this.lblMessages = new global::Gtk.Label ();
			this.lblMessages.Name = "lblMessages";
			this.lblMessages.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Messages:</b>");
			this.lblMessages.UseMarkup = true;
			this.lblMessages.UseUnderline = true;
			this.expndrMessages.LabelWidget = this.lblMessages;
			this.vbox2.Add (this.expndrMessages);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.expndrMessages]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 2;
			w6.Expand = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblNewFilename = new global::Gtk.Label ();
			this.lblNewFilename.Name = "lblNewFilename";
			this.lblNewFilename.Xpad = 15;
			this.lblNewFilename.Xalign = 0F;
			this.lblNewFilename.Ellipsize = ((global::Pango.EllipsizeMode)(2));
			this.vbox2.Add (this.lblNewFilename);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblNewFilename]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblNewFilenameTitle = new global::Gtk.Label ();
			this.lblNewFilenameTitle.Name = "lblNewFilenameTitle";
			this.lblNewFilenameTitle.Xalign = 0F;
			this.lblNewFilenameTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>New filename:</i>");
			this.lblNewFilenameTitle.UseMarkup = true;
			this.vbox2.Add (this.lblNewFilenameTitle);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblNewFilenameTitle]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblOriginalFilename = new global::Gtk.Label ();
			this.lblOriginalFilename.Name = "lblOriginalFilename";
			this.lblOriginalFilename.Xpad = 15;
			this.lblOriginalFilename.Xalign = 0F;
			this.lblOriginalFilename.Ellipsize = ((global::Pango.EllipsizeMode)(2));
			this.vbox2.Add (this.lblOriginalFilename);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblOriginalFilename]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 5;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblOriginalFilenameTitle = new global::Gtk.Label ();
			this.lblOriginalFilenameTitle.Name = "lblOriginalFilenameTitle";
			this.lblOriginalFilenameTitle.Xalign = 0F;
			this.lblOriginalFilenameTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>Original filename:</i>");
			this.lblOriginalFilenameTitle.UseMarkup = true;
			this.vbox2.Add (this.lblOriginalFilenameTitle);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblOriginalFilenameTitle]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 6;
			w10.Expand = false;
			w10.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w11.Position = 0;
			// Internal child Banshee.Renamer.RenamingProgressDialog.ActionArea
			global::Gtk.HButtonBox w12 = this.ActionArea;
			w12.Name = "dialog1_ActionArea";
			w12.Spacing = 10;
			w12.BorderWidth = ((uint)(5));
			w12.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12 [this.buttonCancel]));
			w13.Expand = false;
			w13.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.Sensitive = false;
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12 [this.buttonOk]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 600;
			this.DefaultHeight = 267;
			this.Show ();
		}
	}
}
